### ISSUE TITLE
Cannot start theme...

### ISSUE THREAD

**Issue by coquizen** [miko007/LightDM-Webkit-pantheon-theme#2]
**Issue:**
An attempt to implement the theme results in the following:
Wallpaper -- loaded successfully
Date and Time -- displayed successfully
Menu Bar with the the default icons on the upper right -- loaded successfully?
Login prompt: error. States that there is an error with the the theme and provides a choice of loading a fallback theme or cancel. Clicking any of the three options results in a hang.

**Configuration Files:** The defaults as provided by this git repo.
**Relevant Log Files:**
seat0-greeter.log
```
file:///usr/share/lightdm-webkit/themes/pantheon/javascript/GUI.js:12:60: CONSOLE ERROR TypeError: undefined is not an object (evaluating '$('.user').first().offset().left')
Gdk-Message: lightdm-webkit2-greeter: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.

Gdk-Message: WebKitWebProcess: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
```
Possible reason for the error: I suspect that it is a result of changing the UID and GID of the user in question from the standard UID/GID as utilized by Debian (1000:1000) to the standard as utilized by Apple (501:20). Has this use case been considered or am I barking up the wrong tree? 

Machine: MacbookPro11,1
OS: Dual Booting MacOS Sierra/Debian 9(Stretch)

**Comment by coquizen** [comment]
[Solved] 

Apparently this is a problem with lightdm and accountservice. Removing accountservice via `sudo apt remove accountservice` solves the issue.

**Comment by miko007** [comment]
oh, i never heart of `accountservice` before. i'm glad you solved your issue and the software can be somewhat useful to you.
